CREATE TABLE IF NOT EXISTS SP_SHARD (
    SHARDID INT,
    ORDERID INT,
    SP TEXT,
    DATAID TEXT,
    PRIMARY KEY(SHARDID)
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS index_sp_shard on SP_SHARD(SP);
CREATE INDEX IF NOT EXISTS index_orderid_shard on SP_SHARD(ORDERID);
CREATE INDEX IF NOT EXISTS index_dataid_shard on SP_SHARD(DATAID);
