CREATE TABLE IF NOT EXISTS USER_PROFILE (
    COMMITID TEXT,
    DATAID TEXT,
    CREATEDAT INT,
    UPDATEDAT INT,
    DID TEXT,
    ETHADDR TEXT,
    AVATAR TEXT,
    USERNAME TEXT,
    FOLLOWINGCOUNT INT,
    TWITTER TEXT,
    YOUTUBE TEXT,
    BIO TEXT,
    BANNER TEXT,
    FOLLOWINGDATAID TEXT,
    PRIMARY KEY(COMMITID)
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS index_user_profiles_did on USER_PROFILE(DID);
CREATE INDEX IF NOT EXISTS index_user_profiles_data_id on USER_PROFILE(DATAID);
CREATE INDEX IF NOT EXISTS index_user_profiles_commit_id on USER_PROFILE(COMMITID);