CREATE TABLE IF NOT EXISTS NOTIFICATION (
    BASEDATAID      TEXT,
    CREATEDAT   INTEGER,
    UPDATEDAT   INTEGER,
    MESSAGE     TEXT,
    STATUS      INTEGER,
    MESSAGETYPE      INTEGER,
    FROMUSER    TEXT,
    TOUSER      TEXT,
    PRIMARY KEY(BASEDATAID, MESSAGETYPE)
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS index_notification_from_user on NOTIFICATION(FROMUSER);
CREATE INDEX IF NOT EXISTS index_notification_to_user on NOTIFICATION(TOUSER);
CREATE INDEX IF NOT EXISTS index_notification_status on NOTIFICATION(STATUS);